// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMcBd713_CcQvQ_TQVBF0BmfcpO9i0h-w',
    appId: '1:1018719151807:web:b51c8cc39b4285f8ab880a',
    messagingSenderId: '1018719151807',
    projectId: 'foodapp-69aa5',
    authDomain: 'foodapp-69aa5.firebaseapp.com',
    storageBucket: 'foodapp-69aa5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0nHLVV0A2THuJkqHAs-MfCO-PskaIif8',
    appId: '1:1018719151807:android:2cb8b564d08ae2fbab880a',
    messagingSenderId: '1018719151807',
    projectId: 'foodapp-69aa5',
    storageBucket: 'foodapp-69aa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs54t_Au2GwMst0B5-jnQABG82nWEU7v8',
    appId: '1:1018719151807:ios:6e231ea290392618ab880a',
    messagingSenderId: '1018719151807',
    projectId: 'foodapp-69aa5',
    storageBucket: 'foodapp-69aa5.firebasestorage.app',
    iosBundleId: 'com.example.task2Internship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs54t_Au2GwMst0B5-jnQABG82nWEU7v8',
    appId: '1:1018719151807:ios:6e231ea290392618ab880a',
    messagingSenderId: '1018719151807',
    projectId: 'foodapp-69aa5',
    storageBucket: 'foodapp-69aa5.firebasestorage.app',
    iosBundleId: 'com.example.task2Internship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMcBd713_CcQvQ_TQVBF0BmfcpO9i0h-w',
    appId: '1:1018719151807:web:d93e6a861a7607e1ab880a',
    messagingSenderId: '1018719151807',
    projectId: 'foodapp-69aa5',
    authDomain: 'foodapp-69aa5.firebaseapp.com',
    storageBucket: 'foodapp-69aa5.firebasestorage.app',
  );
}
